name: build on Windows 2022
on:
  workflow_dispatch:
  push:
    tags:
      - Release.*
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: "6.8.3"
  MINGW_VERSION: "win64_mingw"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install zlib with vcpkg
        shell: pwsh
        run: |
          vcpkg install zlib #tbb
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ env.MINGW_VERSION }}
          install-deps: 'true'
          modules: 'qt5compat qthttpserver'
          setup-python: 'false'
          set-env: 'true'
      - name: Configure and build FreeLib
        run: |
          cd ${{github.workspace}}\src\SmtpClient
          cmake -B ${{github.workspace}}\src\SmtpClient\final -DCMAKE_PREFIX_PATH=C:/mingw64/ -DBUILD_TESTS=OFF -DBUILD_DEMOS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles"
          cmake --build ${{github.workspace}}\src\SmtpClient\final --config ${{env.BUILD_TYPE}} -j4
          cmake --install ${{github.workspace}}\src\SmtpClient\final
          tree /F .
          cd ${{github.workspace}}
          cmake --debug-find -DSmtpMime_DIR=${{github.workspace}}\src\SmtpClient\final -DCMAKE_PREFIX_PATH=C:/mingw64/ -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles" -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}} -j4
      - name: always
        if: always()
        run: |
          tree /F
      - name: always
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: |
             ${{github.workspace}}\build
             ${{github.workspace}}\src
             ${{github.workspace}}\build_smtp
      - name: Compress portable program
        run: |
          cd ${{github.workspace}}\build
          windeployqt.exe freelib.exe --release
          Compress-Archive -Path ${{github.workspace}}/build/ -DestinationPath ${{github.workspace}}/build/final.zip
