name: build on Windows 2022
on:
  workflow_dispatch:
  push:
    tags:
      - Release.*
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION:     "6.8.3"
  MINGW_VERSION:  "win64_mingw"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
#      - name: Install Dependencies
#        run: |
#          pip install aqtinstall
#          python -m aqt install-qt windows desktop 6.8.3 win64_mingw
      - name: Install correct version of mingw
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install mingw --version=13.2.0  -y
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ MINGW_VERSION }}
          #dir: '${{ github.workspace }}/qt683/'
          install-deps: 'true'
          # modules: 'qtcharts qtwebengine'
          # archives: 'qtbase qtsvg'
          setup-python: 'false'
          #tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
      - name: (debug) Check QMake, CMake and make
        run: |
          Write-Output (Get-Command qmake.exe).Path
          qmake.exe -version
          Write-Output (Get-Command cmake.exe).Path
          cmake.exe -version
          Write-Output (Get-Command mingw32-make.exe).Path
          mingw32-make.exe -version
      - name: Configure CMake
        #env:
          #CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        #run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -B ${{github.workspace}}/build

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j4
      - name: Compress portable program
        run: |
          ls
          Compress-Archive -Path ${{github.workspace}}\build\all\ -DestinationPath ${{github.workspace}}\build\final.zip

